# example netlify.toml
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "_site"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/home"
  to = "/"

[[redirects]]
  from = "/reception"
  to = "/opening-times"

[[redirects]]
  from = "*"
  to = "/not-found"
  status = 404



  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/

