# example netlify.toml
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/squash"
  to = "https://squash.westwarwicks.club"
  force = true
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  # [dev]
  #  command = "npm run dev" # Command to start your dev server
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
