# example netlify.toml
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "_site"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/home"
  to = "/"

[[redirects]]
  from = "/cloudinaried/:height/:sport/:image"
  to = "https://res.cloudinary.com/andystevenson/image/fetch/c_scale,q_auto,f_auto,h_:height/https://raw.githubusercontent.com/andystevenson/wwsc-assets/master/images/:sport/:image"
  status = 200

[[redirects]]
  from = "/cloudinaried/:sport/:image"
  to = "https://res.cloudinary.com/andystevenson/image/fetch/c_scale,q_auto,f_auto/https://raw.githubusercontent.com/andystevenson/wwsc-assets/master/images/:sport/:image"
  status = 200


[[redirects]]
  from = "*"
  to = "/not-found"
  status = 404

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
[dev]
  command = "npm start" # Command to start your dev server
  publish = "_site" # Folder with the static content for _redirect file


  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
